INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (1, 'Jukka', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (2, 'Jussi', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (3, 'fii', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (4, 'Lari', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (5, 'Sakari', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (6, 'Juri', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (7, 'Janne', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (8, 'Jonni', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (9, 'Mika', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (10, 'Tero', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (11, 'Aaron', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (12, 'Elsa', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (13, 'Krista', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (14, 'Kaj', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (15, 'Kuopion Kaj', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (16, 'Maija', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (17, 'Matti', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (18, 'Kaisa / Matti', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (19, 'Ilpo', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (20, 'Antti', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (21, 'Herkko', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (22, 'Lauri', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (23, 'Timo', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (24, 'Henri', NULL, '1');
INSERT INTO player (id, name, password_hash, permanentAccount) VALUES (25, 'Risto', NULL, '1');


ALTER TABLE game ADD wintemp int;
ALTER TABLE game ADD losetemp int;
ALTER TABLE game ADD thematicmaptemp int;
ALTER TABLE game ADD  unrankedtemp int;
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (1, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'voitto vikalla mahdollisella vuorolla', 0, 0, CAST(N'2019-11-14T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (2, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'tuhottiin neljännes saarta', 0, 0, CAST(N'2019-11-24T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (3, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'voitto ennen 3. stagen kortteja, tuntui helpolta', 0, 0, CAST(N'2019-11-29T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (4, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'tuntui helpolta', 0, 0, CAST(N'2019-11-30T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (5, NULL, 0, 0, 1, 0, NULL, NULL, NULL, N'thematic map', 1, 0, CAST(N'2019-12-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (6, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'oli hilkulla', 0, 0, CAST(N'2019-12-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (7, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'lievä väärinpelaaminen käärmeellä, kompensoitiin', 0, 0, CAST(N'2019-12-12T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (8, NULL, 0, 0, 1, 0, NULL, NULL, NULL, N'hävittiin niukasti pakan loppumiseen, pelattiin Unlock the Gates of Deepest Power kolmesti saman vuoron aikana', 0, 0, CAST(N'2019-12-21T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (9, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'thematic map; eeppiset määrät presenceä laudalla', 1, 0, CAST(N'2020-01-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (10, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-01-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (11, NULL, 78, 1, 0, 0, NULL, NULL, NULL, N'oli helppo', 0, 0, CAST(N'2020-01-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (12, NULL, 0, 0, 1, 0, NULL, NULL, NULL, N'3 lautaa; reilusti turpiin', 0, 0, CAST(N'2020-01-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (13, NULL, 0, 0, 1, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-01-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (14, NULL, 90, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-01-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (15, NULL, 94, 1, 0, 0, NULL, NULL, NULL, N'tuntui helpolta', 0, 0, CAST(N'2020-01-03T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (16, NULL, 108, 1, 0, 0, NULL, NULL, NULL, N'tuntui helpolta, saari lopussa healthy', 0, 0, CAST(N'2020-01-03T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (17, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-01-25T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (18, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'tuntui helpolta', 0, 0, CAST(N'2020-01-25T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (19, NULL, 0, 0, 1, 0, NULL, NULL, NULL, N'turpiin tuli reilusti', 0, 0, CAST(N'2020-01-30T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (20, NULL, 39, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-02-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (21, NULL, 49, 1, 0, 0, NULL, NULL, NULL, N'tuntui suht helpolta, käärme löi koko saarta, saari lopussa healthy', 0, 0, CAST(N'2020-02-09T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (22, NULL, 46, 1, 0, 0, NULL, NULL, NULL, N'tuntui helpolta', 0, 0, CAST(N'2020-02-09T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (23, NULL, 55, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-02-22T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (24, NULL, 67, 1, 0, 0, NULL, NULL, NULL, N'tuntui suht helpolta, henget olivat hyvä kombo', 0, 0, CAST(N'2020-02-23T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (25, NULL, 57, 1, 0, 0, NULL, NULL, NULL, N'tuntui helpolta, saari lopussa healthy', 0, 0, CAST(N'2020-03-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (26, NULL, 64, 1, 0, 0, NULL, NULL, NULL, N'tuntui suht helpolta', 0, 0, CAST(N'2020-03-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (27, NULL, 64, 1, 0, 0, NULL, NULL, NULL, N'tuntui suht helpolta', 0, 0, CAST(N'2020-03-05T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (28, NULL, 76, 1, 0, 0, NULL, NULL, NULL, N'ei mennyt edes kovin tiukaksi', 0, 0, CAST(N'2020-03-05T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (29, NULL, 44, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-05T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (30, NULL, 42, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-05T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (31, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'ei eskalaatiota', 0, 0, CAST(N'2020-03-06T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (32, NULL, 56, 1, 0, 0, NULL, NULL, NULL, N'tuntui pelottavalta mutta ei lopulta ollut edes kovin hilkulla', 0, 0, CAST(N'2020-03-09T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (33, NULL, 51, 1, 0, 0, NULL, NULL, NULL, N'korjattiin yksi häviön aiheuttava ajatusvirhe kesken pelin', 0, 0, CAST(N'2020-03-15T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (34, NULL, 53, 1, 0, 0, NULL, NULL, NULL, N'tuntui olevan hyvin hallinnassa', 0, 0, CAST(N'2020-03-17T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (35, NULL, 64, 1, 0, 0, NULL, NULL, NULL, N'salamalintu teki vikalla vuorolla 22 pelkoa', 0, 0, CAST(N'2020-03-18T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (36, NULL, 62, 1, 0, 0, NULL, NULL, NULL, N'tiukille meni, voitto feariin', 0, 0, CAST(N'2020-03-20T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (37, NULL, 43, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-21T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (38, NULL, 49, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-21T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (39, NULL, 49, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-22T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (40, NULL, 52, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-23T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (41, NULL, 39, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-26T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (42, NULL, 48, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-27T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (43, NULL, 51, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-30T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (44, NULL, 53, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-03-31T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (45, NULL, 57, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-04-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (46, NULL, 61, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-04-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (47, NULL, 50, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-04-04T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (48, NULL, 52, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-04-06T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (49, NULL, 48, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-06-29T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (50, NULL, 29, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-08-30T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (51, NULL, 37, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-09-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (52, NULL, 38, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-09-03T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (53, NULL, 39, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-09-04T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (54, NULL, 40, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-09-07T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (55, NULL, 39, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-09-12T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (56, NULL, 38, 1, 0, 0, NULL, NULL, NULL, N'Elemental Boon, Gift of Nature''s Connection & Gift of Twintempned Days rikkoivat pelin, vuoroilla oli parhaimmillaan 10 ekstraelementtiä', 0, 0, CAST(N'2020-09-24T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (57, NULL, 38, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-10-03T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (58, NULL, 12, 0, 1, 0, NULL, NULL, NULL, N'Järkyttävän huono eventtituuri', 0, 0, CAST(N'2020-10-03T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (59, NULL, 52, 1, 0, 0, NULL, NULL, NULL, N'15 fearin tulva lopetti pelin', 0, 0, CAST(N'2020-10-03T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (60, NULL, 38, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-10-10T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (61, NULL, 43, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-10-23T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (62, NULL, 48, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-10-24T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (63, NULL, 50, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-11-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (64, NULL, 36, 1, 0, 0, NULL, NULL, NULL, N'47 fearin tulivuorenpurkaus (joka tuhosi 10 presenceä ja meni madonreiän kautta toiselle puolelle saarta) lopetti pelin', 0, 0, CAST(N'2020-11-14T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (65, NULL, 53, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-11-15T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (66, NULL, 46, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-11-29T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (67, NULL, 45, 1, 0, 0, NULL, NULL, NULL, N'Tiukoille meni', 0, 0, CAST(N'2020-11-29T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (68, NULL, 19, 0, 1, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-12-07T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (69, NULL, 24, 0, 1, 0, NULL, NULL, NULL, N'Unohdettiin vahtia rannikkokaupunkien määrää', 0, 0, CAST(N'2020-12-07T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (70, NULL, 46, 1, 0, 0, NULL, NULL, NULL, N'tuntui helpohkolta', 0, 0, CAST(N'2020-12-13T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (71, NULL, 19, 0, 1, 0, NULL, NULL, NULL, N'blightia oli joka puolella', 0, 0, CAST(N'2020-12-13T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (72, NULL, 18, 0, 1, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-12-16T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (73, NULL, 59, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2020-12-27T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (74, NULL, 53, 1, 0, 0, NULL, NULL, NULL, N'tuhovoimaa puuttui', 0, 0, CAST(N'2021-01-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (75, NULL, 50, 1, 0, 0, NULL, NULL, NULL, N'blighted island -kortti (All Things Weaken) oli metsäpalolle huonoin mahdollinen', 0, 0, CAST(N'2021-01-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (76, NULL, 49, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-01-17T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (77, NULL, 52, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-01-18T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (78, NULL, 66, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-02-13T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (79, NULL, 71, 1, 0, 0, NULL, NULL, NULL, N'yksi vuoro piti laskea aika tarkasti, pelko pelasti, keskitysleirit (bileet) oli jälleen voittoisa strategia', 0, 0, CAST(N'2021-02-27T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (80, NULL, 49, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-03-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (81, NULL, 45, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-03-09T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (82, NULL, 53, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-03-22T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (83, NULL, 54, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-03-22T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (84, NULL, 62, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-03-22T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (85, NULL, 51, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-04-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (86, NULL, 60, 1, 0, 0, NULL, NULL, NULL, N'tuntui helpolta, Keeperin avustettu Sea monsters teki kerralla 31 fearia', 0, 0, CAST(N'2021-04-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (87, NULL, 22, 0, 1, 0, NULL, NULL, NULL, N'Skenaario: Elemental invocation; blightia tuli kauheasti, hävittiin 8+ damagen ravageihin', 0, 0, CAST(N'2021-04-05T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (88, NULL, 0, 1, 0, 0, NULL, NULL, NULL, N'Skenaario: Varied terrains, thematic map; vaikeustaso oli aika mukava, voitettiin pelkoon tokavikalla kierroksella', 1, 0, CAST(N'2021-04-26T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (89, NULL, 45, 1, 0, 0, NULL, NULL, NULL, N'Skenaario: Varied terrains, thematic map', 1, 0, CAST(N'2021-04-27T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (90, NULL, 19, 0, 1, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-06-10T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (91, NULL, 37, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-06-10T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (92, NULL, 53, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-06-10T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (93, NULL, 38, 1, 0, 0, NULL, NULL, NULL, N'unohdettiin aluksi rannikko-eksploraatiosääntö', 0, 0, CAST(N'2021-06-16T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (94, NULL, 48, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-06-16T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (95, NULL, 14, 0, 1, 0, NULL, NULL, NULL, N'thematic map koko saarella, ei seurattu oikeita sääntöjä setupin suhteen', 1, 2, CAST(N'2021-06-20T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (96, NULL, 48, 1, 0, 0, NULL, NULL, NULL, N'thematic map koko saarella, ei seurattu oikeita sääntöjä setupin suhteen', 1, 2, CAST(N'2021-06-20T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (97, NULL, 45, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-06-20T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (98, NULL, 16, 0, 1, 0, NULL, NULL, NULL, N'huonoa tuuria monella tapaa', 0, 0, CAST(N'2021-06-23T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (99, NULL, 22, 1, 0, 0, NULL, NULL, NULL, N'Skenaario: The Great River', 0, 0, CAST(N'2021-07-08T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (100, NULL, 49, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-07-30T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (101, NULL, 48, 1, 0, 0, NULL, NULL, NULL, N'', 0, 0, CAST(N'2021-07-30T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (102, NULL, 24, 0, 1, 0, NULL, NULL, NULL, N'Skenaario: Guard the Isle''s Heart; kylä sniikkasi huomaamatta saaren keskelle', 0, 0, CAST(N'2021-08-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (103, NULL, 50, 1, 0, 0, NULL, NULL, NULL, N'Skenaario: Guard the Isle''s Heart', 0, 0, CAST(N'2021-08-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (104, NULL, 0, 0, 1, 0, NULL, NULL, NULL, N'Skenaario: Elemental invocation, Thematic map; kylät loppuivat ihan alkuunsa, ikävä eventti sotki pelin ihan totaalisesti', 1, 0, CAST(N'2021-08-15T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (105, NULL, 45, 1, 0, 0, NULL, NULL, NULL, N'Skenaario: Elemental invocation', 0, 0, CAST(N'2021-08-15T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (106, NULL, 45, 1, 0, 0, NULL, NULL, NULL, N'musta aukko puhdisti pöydän', 0, 0, CAST(N'2021-09-11T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (107, NULL, NULL, 1, 0, 0, 1, 2, 3, N'Ensimmäinen peli Elsan setillä', 0, 0, CAST(N'2021-06-12T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (108, NULL, NULL, 0, 1, 2, 6, 10, 10, N'2 islands', 0, 1, CAST(N'2021-06-12T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (109, NULL, NULL, 0, 1, 2, 7, 8, 10, N'2 boards', 0, 1, CAST(N'2021-06-13T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (110, NULL, NULL, 1, 0, 0, 4, 5, 5, N'Blightia enää 2 jäljellä', 0, 0, CAST(N'2021-06-19T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (111, NULL, NULL, 1, 0, 0, 4, 7, 6, N'', 0, 0, CAST(N'2021-06-19T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (112, NULL, NULL, 0, 1, 0, 5, 11, 12, N'Henri pelasi aluksi Lightningilla, Elsa soolona loppuun', 0, 0, CAST(N'2021-06-19T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (113, NULL, NULL, 1, 0, 0, 0, 18, 10, N'Laurin eka peli. Elsa kallio, Lauri joki', 0, 0, CAST(N'2021-08-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (114, NULL, NULL, 1, 0, 0, 6, 5, 6, N'Henrin "kanssa"', 0, 0, CAST(N'2021-08-01T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (115, NULL, NULL, 1, 0, 0, 3, 25, 9, N'Lauri salama, Timo parviäly, Elsa sumu', 0, 0, CAST(N'2021-08-02T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (116, NULL, NULL, 1, 0, 0, 6, 6, 3, N'Henrin kanssa pelattu', 0, 0, CAST(N'2021-08-03T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (117, NULL, NULL, 0, 1, 0, 6, 7, 7, N'Henrin kanssa pelattiin', 0, 0, CAST(N'2021-08-04T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (118, NULL, NULL, 0, 1, 0, 6, 4, 8, N'Eka Keeper-pelini', 0, 0, CAST(N'2021-08-08T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (119, NULL, NULL, 1, 0, 0, 5, 2, 4, N'Terror level 2 -voitto!', 0, 0, CAST(N'2021-08-08T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (120, NULL, NULL, 1, 0, 0, 3, 11, 3, N'Timo metsä, Elsa keeper', 0, 0, CAST(N'2021-08-08T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (121, NULL, NULL, 1, 0, 0, 3, 7, 1, N'', 0, 0, CAST(N'2021-08-15T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (122, NULL, NULL, 0, 1, 0, 5, 8, 4, N'', 0, 0, CAST(N'2021-08-16T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (123, NULL, NULL, 1, 0, 0, 0, 6, 6, N'Huh, tiukille meni. Back against the wall oli hyvä.', 0, 0, CAST(N'2021-08-22T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (124, NULL, NULL, 1, 0, 0, 2, 12, 9, N'Ensimmäinen peli Henrin kanssa oikeilla säännöillä. Elsa tähtivalo, Henri Keeper', 0, 0, CAST(N'2021-09-04T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (125, NULL, NULL, 0, 1, 0, 9, 8, 3, N'Nopea häviö kun eventti lisäsi explorereita ja niitä tuli yhteensä viisi kerralla...(Ranska u know)', 0, 0, CAST(N'2021-09-04T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (126, NULL, NULL, 1, 0, 0, 4, 8, 5, N'Terror level 2 wintemp', 0, 0, CAST(N'2021-09-05T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (127, NULL, NULL, 1, 0, 0, 5, 7, 3, N'(HELPPPO VOITTO', 0, NULL, CAST(N'2021-09-07T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (128, NULL, NULL, 0, 1, 0, 4, 2, 9, N'Sea Monsters jäi harmillisesti pelaamatta, kun hävisin ravagessa. Laudalla 8 wildsia.', 0, NULL, CAST(N'2021-09-07T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (129, NULL, NULL, 0, 1, 0, 5, 4, 7, N'3 rannikkokaupunkia', 0, NULL, CAST(N'2021-09-08T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (130, NULL, NULL, 1, 0, 0, 1, 5, 4, N'Jee Skotlanti level 5 voitettu', 0, NULL, CAST(N'2021-09-11T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (131, NULL, NULL, 1, 0, 0, 2, 7, 3, N'', 0, NULL, CAST(N'2021-09-11T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (132, NULL, NULL, 1, 0, 0, 4, 2, 7, N'Draw towards a consuming void pelattu 3-4 kertaa', 0, NULL, CAST(N'2021-09-11T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (133, NULL, NULL, 1, 0, 0, 5, 9, 2, N'Riston eka peli', 0, NULL, CAST(N'2021-09-15T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (134, NULL, NULL, 1, 0, 0, 2, 4, 4, N'Laivalla Nikan kanssa', 0, NULL, CAST(N'2021-09-19T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (135, NULL, NULL, 0, 1, 0, 1, 9, 7, N'4 fearin päässä voitosta. Huono korttituuri.', 0, NULL, CAST(N'2021-09-21T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (136, NULL, NULL, 0, 1, 0, 5, 6, 8, N'Vaan 2 invaderia laudalla', 0, NULL, CAST(N'2021-09-21T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (137, NULL, NULL, 1, 0, 0, 2, 6, 6, N'Tammistossa Nikan kanssa', 0, NULL, CAST(N'2021-09-23T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (138, NULL, NULL, 0, 1, 0, 5, 5, 11, N'Blightia joka landissa. Tipping ihan kiva blight-kortti tälle hengelle', 0, NULL, CAST(N'2021-09-24T00:00:00.000' AS TIMESTAMP), 0);
INSERT INTO game (id, guid, scoreCustom, wintemp, losetemp, difficultyCustomChange, invaderCardsInDeck, dahan, blight, comment, thematicmaptemp, extraBoards, time, unrankedtemp) VALUES (139, NULL, NULL, 0, 1, 0, 4, 2, 11, N'Huh', 0, NULL, CAST(N'2021-09-24T00:00:00.000' AS TIMESTAMP), 0);


INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (1, 9, 11, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (2, 12, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (3, 24, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (4, 37, 11, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (5, 39, 11, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (6, 40, 11, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (7, 49, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (8, 84, 11, 22);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (9, 95, 11, 24);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (10, 96, 11, 24);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (11, 105, 11, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (12, 97, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (13, 99, 11, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (14, 85, 11, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (15, 41, 11, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (16, 42, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (17, 58, 11, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (18, 64, 11, 24);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (19, 60, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (20, 56, 11, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (21, 53, 11, 23);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (22, 88, 11, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (23, 75, 11, 23);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (24, 76, 11, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (25, 77, 11, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (26, 78, 11, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (27, 79, 11, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (28, 87, 11, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (29, 10, 11, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (30, 11, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (31, 8, 11, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (32, 4, 11, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (33, 13, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (34, 14, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (35, 16, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (36, 17, 11, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (37, 18, 11, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (38, 23, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (39, 57, 11, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (40, 43, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (41, 44, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (42, 45, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (43, 46, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (44, 48, 11, 4);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (45, 103, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (46, 86, 11, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (47, 34, 11, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (48, 35, 11, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (49, 36, 11, 5);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (50, 74, 11, 23);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (51, 62, 11, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (52, 102, 11, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (53, 65, 11, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (54, 54, 11, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (55, 51, 11, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (56, 59, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (57, 15, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (58, 38, 11, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (59, 25, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (60, 26, 11, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (61, 73, 11, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (62, 71, 11, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (63, 68, 11, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (64, 69, 11, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (65, 70, 11, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (66, 104, 11, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (67, 67, 11, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (68, 89, 11, 24);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (69, 92, 11, 18);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (70, 81, 11, 18);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (71, 106, 11, 20);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (72, 61, 11, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (73, 66, 11, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (74, 52, 11, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (75, 7, 20, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (76, 7, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (77, 6, 12, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (78, 10, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (79, 22, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (80, 20, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (81, 21, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (82, 94, 12, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (83, 29, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (84, 93, 12, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (85, 97, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (86, 96, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (87, 95, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (88, 49, 12, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (89, 9, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (90, 5, 12, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (91, 92, 12, 20);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (92, 91, 12, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (93, 1, 12, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (94, 30, 12, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (95, 27, 12, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (96, 28, 12, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (97, 26, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (98, 25, 12, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (99, 100, 12, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (100, 101, 12, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (101, 90, 12, 20);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (102, 32, 12, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (103, 33, 12, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (104, 33, 3, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (105, 55, 3, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (106, 43, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (107, 86, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (108, 103, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (109, 47, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (110, 48, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (111, 100, 3, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (112, 34, 3, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (113, 90, 3, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (114, 62, 3, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (115, 74, 3, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (116, 36, 3, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (117, 35, 3, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (118, 32, 3, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (119, 102, 3, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (120, 101, 3, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (121, 63, 3, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (122, 59, 3, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (123, 65, 3, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (124, 51, 3, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (125, 54, 3, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (126, 25, 3, 5);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (127, 26, 3, 5);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (128, 15, 3, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (129, 38, 3, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (130, 19, 3, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (131, 72, 3, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (132, 28, 3, 5);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (133, 73, 3, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (134, 27, 3, 5);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (135, 68, 3, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (136, 71, 3, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (137, 2, 3, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (138, 70, 3, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (139, 69, 3, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (140, 30, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (141, 104, 3, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (142, 50, 3, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (143, 31, 3, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (144, 1, 3, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (145, 67, 3, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (146, 83, 3, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (147, 91, 3, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (148, 89, 3, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (149, 92, 3, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (150, 81, 3, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (151, 66, 3, 20);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (152, 106, 3, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (153, 5, 3, 5);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (154, 61, 3, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (155, 52, 3, 18);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (156, 12, 3, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (157, 24, 3, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (158, 39, 3, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (159, 37, 3, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (160, 40, 3, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (161, 49, 3, 5);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (162, 9, 3, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (163, 84, 3, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (164, 96, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (165, 95, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (166, 105, 3, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (167, 97, 3, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (168, 98, 3, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (169, 80, 3, 23);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (170, 29, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (171, 60, 3, 23);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (172, 56, 3, 22);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (173, 53, 3, 15);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (174, 64, 3, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (175, 93, 3, 23);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (176, 82, 3, 23);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (177, 58, 3, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (178, 42, 3, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (179, 85, 3, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (180, 41, 3, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (181, 99, 3, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (182, 18, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (183, 20, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (184, 17, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (185, 16, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (186, 14, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (187, 21, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (188, 22, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (189, 23, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (190, 57, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (191, 46, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (192, 45, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (193, 44, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (194, 11, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (195, 10, 3, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (196, 7, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (197, 6, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (198, 4, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (199, 13, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (200, 8, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (201, 3, 3, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (202, 87, 3, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (203, 79, 3, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (204, 78, 3, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (205, 77, 3, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (206, 76, 3, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (207, 75, 3, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (208, 94, 3, 22);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (209, 88, 3, 15);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (210, 17, 21, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (211, 18, 21, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (212, 64, 21, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (213, 52, 21, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (214, 54, 21, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (215, 30, 19, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (216, 104, 7, 18);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (217, 67, 7, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (218, 66, 7, 15);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (219, 61, 7, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (220, 81, 7, 4);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (221, 89, 7, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (222, 83, 7, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (223, 63, 7, 18);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (224, 102, 7, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (225, 72, 7, 23);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (226, 62, 7, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (227, 103, 7, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (228, 82, 7, 22);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (229, 80, 7, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (230, 105, 7, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (231, 84, 7, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (232, 55, 8, 18);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (233, 33, 8, 4);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (234, 49, 1, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (235, 64, 6, 18);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (236, 18, 6, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (237, 17, 6, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (238, 53, 6, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (239, 31, 2, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (240, 2, 18, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (241, 62, 14, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (242, 19, 14, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (243, 15, 14, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (244, 3, 14, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (245, 98, 14, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (246, 55, 13, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (247, 23, 15, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (248, 60, 4, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (249, 33, 16, 12);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (250, 2, 16, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (251, 50, 16, 20);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (252, 50, 17, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (253, 50, 9, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (254, 59, 9, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (255, 58, 9, 18);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (256, 95, 9, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (257, 99, 9, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (258, 97, 9, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (259, 96, 9, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (260, 22, 9, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (261, 57, 9, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (262, 21, 9, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (263, 20, 9, 4);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (264, 84, 5, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (265, 105, 5, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (266, 85, 5, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (267, 80, 5, 14);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (268, 82, 5, 5);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (269, 102, 5, 15);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (270, 86, 5, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (271, 103, 5, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (272, 104, 5, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (273, 83, 5, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (274, 89, 5, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (275, 81, 5, 16);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (276, 61, 5, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (277, 2, 10, 4);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (278, 107, 12, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (279, 108, 12, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (280, 109, 12, 9);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (281, 110, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (282, 111, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (283, 112, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (284, 112, 12, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (285, 113, 12, 3);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (286, 113, 22, 2);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (287, 114, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (288, 115, 12, 19);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (289, 115, 22, 1);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (290, 115, 23, 17);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (291, 116, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (292, 117, 12, 15);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (293, 118, 12, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (294, 119, 12, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (295, 120, 12, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (296, 120, 23, 6);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (297, 121, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (298, 122, 12, 8);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (299, 123, 12, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (300, 124, 12, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (301, 124, 24, 10);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (302, 125, 12, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (303, 126, 12, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (304, 127, 12, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (305, 128, 12, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (306, 129, 12, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (307, 130, 12, 7);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (308, 131, 12, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (309, 132, 12, 21);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (310, 133, 12, 20);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (311, 133, 25, 13);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (312, 134, 12, 15);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (313, 135, 12, 15);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (314, 136, 12, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (315, 137, 12, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (316, 138, 12, 11);
INSERT INTO game_player_spirit (id, gameId, playerId, spiritId) VALUES (317, 139, 12, 11);



INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (1, 1, 25);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (2, 2, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (3, 3, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (4, 4, 19);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (5, 5, 11);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (6, 6, 11);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (7, 7, 12);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (8, 8, 20);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (9, 9, 5);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (10, 10, 10);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (11, 11, 24);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (12, 12, 24);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (13, 13, 25);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (14, 14, 25);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (15, 15, 25);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (16, 16, 26);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (17, 17, 11);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (18, 18, 12);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (19, 19, 24);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (20, 20, 4);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (21, 21, 5);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (22, 22, 5);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (23, 23, 25);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (24, 24, 26);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (25, 25, 26);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (26, 26, 27);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (27, 27, 27);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (28, 28, 28);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (29, 29, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (30, 30, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (31, 31, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (32, 32, 12);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (33, 33, 12);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (34, 34, 12);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (35, 35, 13);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (36, 36, 14);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (37, 37, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (38, 38, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (39, 39, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (40, 40, 19);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (41, 41, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (42, 42, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (43, 43, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (44, 44, 19);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (45, 45, 20);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (46, 46, 21);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (47, 47, 19);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (48, 48, 3);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (49, 48, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (50, 49, 19);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (51, 50, 44);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (52, 51, 30);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (53, 52, 45);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (54, 53, 45);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (55, 54, 45);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (56, 55, 45);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (57, 56, 45);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (58, 57, 38);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (59, 58, 46);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (60, 59, 46);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (61, 60, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (62, 61, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (63, 62, 46);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (64, 63, 46);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (65, 64, 46);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (66, 65, 47);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (67, 66, 39);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (68, 67, 47);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (69, 68, 47);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (70, 69, 47);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (71, 70, 32);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (72, 71, 33);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (73, 72, 47);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (74, 73, 33);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (75, 74, 39);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (76, 75, 39);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (77, 76, 39);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (78, 77, 40);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (79, 78, 41);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (80, 79, 42);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (81, 80, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (82, 81, 32);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (83, 82, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (84, 83, 19);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (85, 84, 20);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (86, 85, 47);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (87, 86, 48);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (88, 87, 33);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (89, 90, 39);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (90, 91, 38);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (91, 92, 39);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (92, 93, 45);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (93, 94, 46);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (94, 97, 46);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (95, 98, 45);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (96, 100, 39);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (97, 101, 40);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (98, 102, 47);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (99, 103, 47);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (100, 104, 24);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (101, 105, 24);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (102, 106, 4);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (103, 110, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (104, 111, 16);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (105, 117, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (106, 118, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (107, 119, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (108, 120, 17);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (109, 121, 9);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (110, 122, 11);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (111, 123, 11);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (112, 125, 24);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (113, 126, 24);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (114, 127, 46);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (115, 128, 48);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (116, 129, 48);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (117, 130, 48);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (118, 131, 10);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (119, 132, 12);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (120, 134, 12);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (121, 135, 19);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (122, 136, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (123, 137, 18);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (124, 138, 12);
INSERT INTO game_adversaryLevel (id, gameId, adversaryLevelId) VALUES (125, 139, 12);

ALTER TABLE game ADD wintemp int;
ALTER TABLE game ADD losetemp int;
ALTER TABLE game ADD thematicmaptemp int;
ALTER TABLE game ADD  unrankedtemp int;

update game set win = CAST(wintemp as bit);
update game set lose = CAST(losetemp as bit);
update game set thematicmap = CAST(thematicmaptemp as bit);
update game set unranked = CAST(unrankedtemp as bit);

ALTER TABLE game DROP COLUMN wintemp;
ALTER TABLE game DROP COLUMN losetemp;
ALTER TABLE game DROP COLUMN thematicmaptemp;
ALTER TABLE game DROP COLUMN  unrankedtemp;